import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppProvider from "../providers/AppProviderContext";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Blank NextJS App",
  description: "Generated by create next app; blanked by Ryan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        {/* AppProvider houses all app provides under one roof. Global app context files found at @/providers */}
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
